#!/bin/bash

# Dotfiles Install
#
# Running this script will symlink these dotfiles to their appropriate
# locations, making the directories if they do not exist. It uses the
# -f flag to link, so it can be run, even if the symlinks already exists.

# to use absolute symlinks
pwd=$(pwd)

# link vimrc
ln -s $pwd/vimrc ~/.vimrc

# link vim filetype plugins
mkdir -p ~/.vim
ln -s $pwd/vim/ftplugin ~/.vim/ftplugin

# link bashrc
ln -s $pwd/bashrc ~/.bashrc

# link tmux conf
ln -s $pwd/tmux.conf ~/.tmux.conf

# make neovim symlinks (:help nvim_from_vim)
mkdir -p ${XDG_CONFIG_HOME:=$HOME/.config}
ln -s ~/.vim $XDG_CONFIG_HOME/nvim
ln -s ~/.vimrc $XDG_CONFIG_HOME/nvim/init.vim

# link i3 config
#ln -s $pwd/i3 ~/.i3
#ln -s $pwd/i3blocks.conf ~/.i3blocks.conf

