#!/bin/bash

set -euo pipefail

# manual steps
# - remap fn to ctrl
# - remap caps to esc
# - disable trackpad "lookup and data detectors"
# - encrypt disk

# disable startup sound
sudo nvram SystemAudioVolume=" "

# reverse trackpad scroll direction
defaults write NSGlobalDomain com.apple.swipescrolldirection -bool true

# enable tap to click
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# enable key repeat
defaults write -g ApplePressAndHoldEnabled -bool false

# screenshots path
defaults write com.apple.screencapture location ~/Pictures/Screenshots

# enable key repeats
defaults write -g InitialKeyRepeat -int 10
defaults write -g KeyRepeat -int 1

# disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# disable the untrusted apps dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# enable quitting finder
defaults write com.apple.finder QuitMenuItem -bool YES

# show hidden files in finder
defaults write com.apple.finder AppleShowAllFiles -bool true

# autohide the dock
defaults write com.apple.dock "autohide" -bool "true"

# use less jarring animation for minimize
defaults write com.apple.dock "mineffect" -string "scale"

# restart affected processes
killall Dock
killall Finder

# install xcode command line tools (ignore error if already installed)
xcode-select --install || true

# install brew
if [[ ! -d /opt/homebrew ]] ; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

brew analytics off
brew install git
brew install jq
brew install --cask visual-studio-code
brew install --cask google-chrome
brew install --cask spotify
brew install --cask tableplus
pip3 install awscli --upgrade --user
code --install-extension vscodevim.vim
code --install-extension github.github-vscode-theme
code --install-extension geddski.macros

# install nvm
if [[ ! -d ~/.nvm ]] ; then
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
fi

# link everything
DOTFILES=$PWD
VSCODE_DIR=~/Library/Application\ Support/Code/User

ln -sfn $DOTFILES/.vim ~/.vim
ln -sf $DOTFILES/.vimrc ~/.vimrc
ln -sf $DOTFILES/.zshrc ~/.zshrc
ln -sf $DOTFILES/.zshenv ~/.zshenv
ln -sf $DOTFILES/.tmux.conf ~/.tmux.conf
ln -sf $DOTFILES/vscode/settings.json "$VSCODE_DIR/settings.json"
ln -sf $DOTFILES/vscode/keybindings.json "$VSCODE_DIR/keybindings.json"
