#!/usr/bin/env bash

root=$(pwd)

mkdir -p ~/.config

ln -f -s $root/tmux.conf ~/.tmux.conf
ln -f -s $root/vimrc ~/.vimrc
ln -f -s $root/nvim ~/.config/nvim
ln -f -s $root/zshrc ~/.zshrc
ln -f -s $root/zshenv ~/.zshenv
ln -f -s $root/vscode/settings.json ~/Library/Application\ Support/Code/User/settings.json
ln -f -s $root/vscode/keybindings.json ~/Library/Application\ Support/Code/User/keybindings.json

#ln -f -s $(root)/spectacle.json ~/Library/Application\ Support/Spectacle/Shortcuts.json
