#!/usr/bin/env bash

ln -f -s $(pwd)/tmux.conf ~/.tmux.conf
ln -f -s $(pwd)/vimrc ~/.vimrc
ln -f -s $(pwd)/nvim ~/.config/nvim
ln -f -s $(pwd)/zshrc ~/.zshrc
ln -f -s $(pwd)/zshenv ~/.zshenv
ln -f -s $(pwd)/spectacle.json ~/Library/Application\ Support/Spectacle/Shortcuts.json
